### ISSUE TITLE
text inside hero is displaying bottom of the screen

### ISSUE THREAD

**Issue by pavanbomale** [pavankpdev/netflix-clone-shapeai-bootcamp#1]
Text inside hero is displaying to bottom of the screen

**Comment by pavanbomale** [comment]
Text inside hero is displaying to bottom of the screen for iPad device

**Comment by Paadmaa** [comment]
It is really easy, and nice to navigate.you are doing a great job, and up to date with technology....
It is my privilege to learn HTML&CSS with you..
Thank you so much sir 😊

**Comment by Padma-78** [comment]
Gero

**Comment by Paadmaa** [comment]
Hero
